name:  Telegram Daily Report

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  daily-report:
    runs-on: ubuntu-latest
    steps:
      - name:  Checkout
        uses: actions/checkout@v3
      - name:  Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name:  Install
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests python-dotenv
      - name:  Run Report
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python daily_telegram_report.py
